#!/usr/bin/env bash

# unsnap - a tool to migrate away from snaps
# shellcheck disable=SC2129

# Define some ANSI colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[0;37m'
NC='\033[0m' # No Color


function display_warnings() {
    echo -e "${YELLOW}WARNING:${NC} Care has been taken to ensure this script is safe."
    echo "The generated scripts will remove applications and data."
    echo "Please ensure you have backups in case you need to recover data."
    echo "Also note significant disk space may be required to migrate,"
    echo "while both snaps and equivalent flatpaks are installed."
    read -r -p "Press enter now to continue or CTRL+C to abort."
}

function setup_environment() {
    DATETIMESTAMP=$(date +%Y-%m-%d.%H.%M.%S)
    LOGDIR="./log-$DATETIMESTAMP"
    LOGFILE="$LOGDIR/unsnap.log"
    INSTALLEDSNAPLIST="$LOGDIR/allsnaps.txt"
    FILTEREDSNAPLIST="$LOGDIR/filteredsnaps.txt"
    MISSINGFLATPAK="$LOGDIR/missingflatpak.txt"
    APPLIST="./applist.csv"
    EXCLUDEDSNAPLIST="./excluded_snaps.txt"
    BACKUPSCRIPT="$LOGDIR/00-backup"
    INSTALLFLATPACKSCRIPT="$LOGDIR/01-install-flatpak"
    ENABLEFLATHUBSRIPT="$LOGDIR/02-enable-flathub"
    INSTALLPACKAGESSCRIPT="$LOGDIR/03-install-flatpaks"
    REMOVESNAPSSCRIPT="$LOGDIR/04-remove-snaps"
    REMOVESNAPDSCRIPT="$LOGDIR/99-remove-snapd"
    SHEBANG="#!/usr/bin/env bash"
    RECOMMENDREBOOT="no"
    REBOOTTEXT="${YELLOW}WARNING:${NC} Please logout/in or reboot, to ensure applications appear in your desktop menu"
    PACKAGEMGR="unknown"
}

function create_logdir() {
    mkdir "$LOGDIR"
}

function audit_snap() {
    # TODO: Change these to not require snap, but use a reliable API instead
    echo -n "INFO: Audit snap $1" | tee -a "$LOGFILE"
    if snap info "$1" > /dev/null; then 
        echo " ✔" | tee -a "$LOGFILE"
    else
        echo " ✖" | tee -a "$LOGFILE"
    fi
}

function audit_flatpak() {
    # Check if a flatpak exists in the currently configured remotes
    # TODO: Change these to not require flatpak execution, but use a reliable API instead
    echo -n "INFO: Audit flatpak $1" | tee -a "$LOGFILE"
    if flatpak search "$1" > /dev/null; then 
        echo " ✔" | tee -a "$LOGFILE"
    else
        echo " ✖" | tee -a "$LOGFILE"
    fi
}

function check_applist() {
    # Called by 'unsnap check'
    # Iterates through the csv file containing mapping of snap,flatpak to see 
    # if the snap and flatpak actually exist on the snap store and flathub
    # This should really only be used by developers of unsnap, to verify that the
    # applist.csv data is sane/valid
    while IFS="" read -r p || [ -n "$p" ]
    do
        snap=$(echo "$p" | awk -F ',' '{ print $1}')
        flatpak=$(echo "$p" | awk -F ',' '{ print $2}')
        audit_snap "$snap"
        audit_flatpak "$flatpak"
    done < "$APPLIST"
    exit 0
}

function check_for_snap() {
    # Check for the existence of a an executable snap binary.
    # If snap doesn't exist or work, likelyhood is no snaps are installed either
    # so we exit out.
    echo -e "${GREEN}INFO:${NC} Checking for snap binary"  | tee -a "$LOGFILE"
    if [ -x "$(command -v snap)" ]; then
        echo -e "${GREEN}INFO:${NC} snap found" | tee -a "$LOGFILE"
    else
       echo -e "${RED}ERROR:${NC} snapd doesn't appear to be installed, exiting." | tee -a "$LOGFILE"
        exit 1
    fi
    echo -e "${GREEN}INFO:${NC} Check for any snaps installed" | tee -a "$LOGFILE"
    if [ "$(snap list | wc -l)" == "0" ]; then 
       echo -e "${RED}ERROR:${NC} No snaps installed, nothing to do here!" | tee -a "$LOGFILE"
        exit 6
    fi
}

function generate_flatpak_install_script() {
    # Generate shell script to install flatpak itself
    # As flatpak binary may not be installed (especially on Ubuntu and some derivatives)
    # TODO: We assume use of sudo here, which we really shouldn't, but instead tell user
    # to run script using sudo or root.
    echo -e "${GREEN}INFO:${NC} Generating flatpak installer script in $INSTALLFLATPACKSCRIPT" | tee -a "$LOGFILE"
    echo "$SHEBANG" > "$INSTALLFLATPACKSCRIPT"
    echo "# Documentation: https://flatpak.org/setup/" >> "$INSTALLFLATPACKSCRIPT"
    case $PACKAGEMGR in
        apt)
        cat <<EOT >> "$INSTALLFLATPACKSCRIPT"
sudo apt update
sudo apt install flatpak
# sudo apt install gnome-software-plugin-flatpak
EOT
            ;;
        pacman)
        cat <<EOT >> "$INSTALLFLATPACKSCRIPT"
sudo pacman -Syu
sudo pacman -S flatpak
EOT
            ;;
        zypper)
        cat <<EOT >> "$INSTALLFLATPACKSCRIPT"
sudo zypper refresh
sudo zypper install flatpak
EOT
            ;;
        dnf)
        cat <<EOT >> "$INSTALLFLATPACKSCRIPT"
sudo dnf update
sudo dnf install flatpak
EOT
            ;;
        yum)
        cat <<EOT >> "$INSTALLFLATPACKSCRIPT"
sudo yum update
sudo yum install flatpak
EOT
            ;;
        eopkg)
        cat <<EOT >> "$INSTALLFLATPACKSCRIPT"
sudo eopkg install flatpak
EOT
            ;;
        *)
           echo -e "${RED}ERROR:${NC} Unable to generate flatpak install script. Unimplemented Package Manager." | tee -a "$LOGFILE"
            exit 5
    esac
    RECOMMENDREBOOT="yes"
    echo "echo $REBOOTTEXT" >> "$INSTALLFLATPACKSCRIPT"
    chmod +x "$INSTALLFLATPACKSCRIPT"
}

function generate_packages_install_script() {
    # Generate shell script to install each flatpak in turn
    # TODO: Should also wrap each install to detect if it fails, and stop to cope
    # with error situations like disk full.
    echo -e "${GREEN}INFO:${NC} Generating flatpaks installer script in $INSTALLPACKAGESSCRIPT" | tee -a "$LOGFILE"
    echo "$SHEBANG" > "$INSTALLPACKAGESSCRIPT"
    echo -n "for f in " >> "$INSTALLPACKAGESSCRIPT"
    while IFS="" read -r p || [ -n "$p" ]
    do
        snap=$p
        flatpak=$(grep "^$p" "$APPLIST" | awk -F ',' '{ print $2}')
        if [ "$flatpak" == "" ]; then
            echo -e "${YELLOW}WARNING:${NC} No equivalent flatpak for $snap found" | tee -a "$LOGFILE"
            echo "$snap" >> "$MISSINGFLATPAK"
        else
            echo -n "$flatpak " >> "$INSTALLPACKAGESSCRIPT"
        fi
    done < "$FILTEREDSNAPLIST"
    echo -n " ;" >> "$INSTALLPACKAGESSCRIPT"
    echo " do" >> "$INSTALLPACKAGESSCRIPT"
    echo "  flatpak install flathub --noninteractive -y \$f" >> "$INSTALLPACKAGESSCRIPT"
    echo "done" >> "$INSTALLPACKAGESSCRIPT"
    chmod +x "$INSTALLPACKAGESSCRIPT"
}

function generate_flathub_enablement_script() {
    # Generate short script to enable flathub which is required if
    # the user hasn't already enabled it as (currently) all the applications we 
    # install are from flathub - but this could change in the future.
    # flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    echo -e "${GREEN}INFO:${NC} Generating flathub enablement script in $ENABLEFLATHUBSRIPT" | tee -a "$LOGFILE"
    echo "$SHEBANG" > "$ENABLEFLATHUBSRIPT" 
    echo "sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo" >> "$ENABLEFLATHUBSRIPT"
    chmod +x "$ENABLEFLATHUBSRIPT"
}

function generate_remove_snaps_script() {
    # Generate a shell script to remove each snap in turn.
    echo -e "${GREEN}INFO:${NC} Generating snap removal script in $REMOVESNAPSSCRIPT" | tee -a "$LOGFILE"
    echo "$SHEBANG" > "$REMOVESNAPSSCRIPT" 
    echo -n "for s in " >> "$REMOVESNAPSSCRIPT"
    while IFS="" read -r p || [ -n "$p" ]
    do
        snap=$(echo "$p" | awk -F ',' '{ print $1}')
        echo -n "$snap " >> "$REMOVESNAPSSCRIPT"
    done < "$FILTEREDSNAPLIST"
    echo -n " ;" >> "$REMOVESNAPSSCRIPT"
    echo " do" >> "$REMOVESNAPSSCRIPT"
    echo "  sudo snap remove \$s " >> "$REMOVESNAPSSCRIPT"
    echo "done" >> "$REMOVESNAPSSCRIPT"
    chmod +x "$REMOVESNAPSSCRIPT"
}

function generate_remove_snapd_script() {
    # Generate shell script to remove snapd.
    # Needs to use distro specific commands to do this via the appropriate
    # package manager
    # Note that currently we assume sudo, but for some distros, that won't work
    # so we might be better off removing all references to sudo, and inform the user
    # to run the script as "root user or sudo as appropriate".
    echo -e "${GREEN}INFO:${NC} Generating snapd removal script in $REMOVESNAPDSCRIPT" | tee -a "$LOGFILE"
    echo "$SHEBANG" > "$REMOVESNAPDSCRIPT" 
    echo "echo Removing snapd" >> "$REMOVESNAPDSCRIPT" 
    case $PACKAGEMGR in
        apt)
            echo "sudo apt remove snapd" >> "$REMOVESNAPDSCRIPT"
            ;;
        pacman)
            echo "sudo pacman -Rsn snapd" >> "$REMOVESNAPDSCRIPT"
            ;;
        zypper)
            echo "sudo zypper remove snapd" >> "$REMOVESNAPDSCRIPT"
            ;;
        dnf)
            echo "sudo dnf remove snapd" >> "$REMOVESNAPDSCRIPT"
            ;;
        yum)
            echo "sudo yum remove snapd" >> "$REMOVESNAPDSCRIPT"
            ;;
        eopkg)
            echo "sudo eopkg remove snapd" >> "$REMOVESNAPDSCRIPT"
            ;;
        *)
           echo -e "${RED}ERROR:${NC} Unable to generate snapd removal script. Unimplemented package manager." | tee -a "$LOGFILE"
    esac
    chmod +x "$REMOVESNAPDSCRIPT"
}

function generate_backup_script() {
    # Generate shell script which will use snap save to snapshot each application user data
    # We snapshot all snaps, even if only some of them are being replaced, because the user
    # might run the 'remove snapd' script, which will nuke all their snaps, not just migrated
    # ones.
    # Not all snaps store data in their own directory - classic snaps being a good culprit
    echo -e "${GREEN}INFO:${NC} Generating snap backup script in $BACKUPSCRIPT"  | tee -a "$LOGFILE"
    echo "$SHEBANG" > "$BACKUPSCRIPT" 
    echo "# Documentation: https://snapcraft.io/docs/snapshots" >> "$BACKUPSCRIPT"
    echo -n "snap save " >> "$BACKUPSCRIPT"
    while IFS="" read -r p || [ -n "$p" ]
    do
        snap=$(echo "$p" | awk -F ',' '{ print $1}')
        echo -n "$snap " >> "$BACKUPSCRIPT"
    done < "$FILTEREDSNAPLIST"
    echo "" >> "$BACKUPSCRIPT"
    chmod +x "$BACKUPSCRIPT"
}

function check_for_flatpak() {
    # Check if the flatpak binary exists, and if it doesn't call 
    # function to generate a script to install flatpak
    echo -e "${GREEN}INFO:${NC} Checking for flatpak binary" | tee -a "$LOGFILE"
    if [ -x "$(command -v flatpak)" ]; then
        echo -e "${GREEN}INFO:${NC} flatpak found no need to generate flatpak install script" | tee -a "$LOGFILE"
        check_for_flathub
    else
        echo -e "${GREEN}INFO:${NC} flatpak doesn't appear to be installed, adding installer script and enabling flathub" | tee -a "$LOGFILE"
        generate_flatpak_install_script
        generate_flathub_enablement_script
    fi
}

function check_for_flathub() {
    # Check if flathub is a configured remote and if not, call function to 
    # generate a script which enables it.
    echo -e "${GREEN}INFO:${NC} Checking for flathub remote" | tee -a "$LOGFILE"
    if flatpak remotes | grep flathub > /dev/null; then
        echo -e "${GREEN}INFO:${NC} flathub already enabled" |  tee -a "$LOGFILE"
    else
        echo -e "${GREEN}INFO:${NC} flathub doesn't appear to be enabled" |  tee -a "$LOGFILE"
        generate_flathub_enablement_script
    fi
}

function determine_packagemanager() {
    # Figure out what package manager is base to the current system on so we can use appropriate commands
    # later for installing / removing snapd and installing flatpak
    PACKAGEMGR=$(command -v {apt,pacman} | sed "s/.*\///")
    case $PACKAGEMGR in
        apt|pacman|zypper|dnf|yum|eopkg)
            PACKAGEMGR="$PACKAGEMGR"
            ;;
        *)
           echo -e "${RED}ERROR:${NC} Could not determine appropriate package manager, '$PACKAGEMGR' aborting" | tee -a "$LOGFILE"
            exit 2
            ;;
    esac
    echo -e "${GREEN}INFO:${NC} Detected $PACKAGEMGR as package manager" | tee -a "$LOGFILE"
}

function get_installed_snaps() {
    # Get list of currently installed snaps on this machine
    # Then filter out excluded snaps, for which we know there is no
    # equivalent in flathub (such as platform / theme snaps)
    echo -e "${GREEN}INFO:${NC} Getting list of installed snaps to $INSTALLEDSNAPLIST" | tee -a "$LOGFILE"
    snap list | tail -n +2 | awk -F " " '{ print $1 }' > "$INSTALLEDSNAPLIST"
    echo -e "${GREEN}INFO:${NC} Trimming list of installed snaps to $FILTEREDSNAPLIST" | tee -a "$LOGFILE"
    grep -v -f "$EXCLUDEDSNAPLIST" "$INSTALLEDSNAPLIST" > "$FILTEREDSNAPLIST"
}

function cleanup() {
    # Remove working files created during unsnap run
    rm "$INSTALLEDSNAPLIST" "$FILTEREDSNAPLIST"
}

function run_scripts() {
    # Run the actual scripts one by one, stopping on error
    echo -e "${GREEN}INFO:${NC} Running backup" | tee -a "$LOGFILE"
    if "$BACKUPSCRIPT"; then
        echo -e "${GREEN}INFO:${NC} Backup finished" | tee -a "$LOGFILE"
    else
       echo -e "${RED}ERROR:${NC} Backup failed" | tee -a "$LOGFILE"
        exit 10
    fi
    if test -f "$INSTALLFLATPACKSCRIPT"; then
        echo -e "${GREEN}INFO:${NC} Installing flatpak" | tee -a "$LOGFILE"
        if "$INSTALLFLATPACKSCRIPT"; then
            echo -e "${GREEN}INFO:${NC} Installing flatpak finished" | tee -a "$LOGFILE"
        else
           echo -e "${RED}ERROR:${NC} Install flatpak failed" | tee -a "$LOGFILE"
            exit 11
        fi
    else
        echo -e "${GREEN}INFO:${NC} Skipping installing flatpak, already installed" | tee -a "$LOGFILE"
    fi
    if test -f "$ENABLEFLATHUBSRIPT"; then
        echo -e "${GREEN}INFO:${NC} Enabling flathub" | tee -a "$LOGFILE"
        if "$ENABLEFLATHUBSRIPT"; then
            echo -e "${GREEN}INFO:${NC} Flathub enabled" | tee -a "$LOGFILE"
        else
           echo -e "${RED}ERROR:${NC} Enabling flathub failed" | tee -a "$LOGFILE"
            exit 12
        fi
    else
        echo -e "${GREEN}INFO:${NC} Skipping enabling flathub, already enabled" | tee -a "$LOGFILE"
    fi
    echo -e "${GREEN}INFO:${NC} Installing flatpak packages" | tee -a "$LOGFILE"
    if "$INSTALLPACKAGESSCRIPT"; then
        echo -e "${GREEN}INFO:${NC} flatpaks installed" | tee -a "$LOGFILE"
    else
       echo -e "${RED}ERROR:${NC} Failed to install flatpaks" | tee -a "$LOGFILE"
        exit 13
    fi
    echo -e "${GREEN}INFO:${NC} Removing snaps" | tee -a "$LOGFILE"
    if "$REMOVESNAPSSCRIPT"; then
        echo -e "${GREEN}INFO:${NC} Snaps removed" | tee -a "$LOGFILE"
    else
       echo -e "${RED}ERROR:${NC} Failed to remove snaps" | tee -a "$LOGFILE"
        exit 14
    fi
    echo -e "${GREEN}INFO:${NC} Removing snapd daemon" | tee -a "$LOGFILE"
    if "$REMOVESNAPDSCRIPT"; then
        echo -e "${GREEN}INFO:${NC} snapd removed" | tee -a "$LOGFILE"
    else
       echo -e "${RED}ERROR:${NC} Failed to remove snapd" | tee -a "$LOGFILE"
        exit 15
    fi
}

function recommend_reboot() {
    if [ "$RECOMMENDREBOOT" == "yes" ]; then
        echo "$REBOOTTEXT" | tee -a "$LOGFILE"
    fi
}


setup_environment
if [ "$1" == "check" ]; then
    create_logdir
    echo -e "${GREEN}INFO:${NC} Check requested" | tee -a "$LOGFILE"
    check_applist
else
    display_warnings
    create_logdir
fi

check_for_snap # this should be universal, so we can check for the binary earlier for check_snap
check_for_flatpak # this should be universal check maybe, so it can be checked in "check_flatpak"
determine_packagemanager
get_installed_snaps
generate_backup_script
generate_packages_install_script
generate_remove_snaps_script
generate_remove_snapd_script
cleanup
if [ "$1" == "auto" ]; then
    echo -e "${GREEN}INFO:${NC} Auto requested" | tee -a "$LOGFILE"
    run_scripts
    recommend_reboot
fi
